version: '3.8'

services:
  kube-migrate-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
      - ALLOWED_ORIGIN=*
      # Add other environment variables as needed
      # - VITE_SUPABASE_URL=your_supabase_url
      # - VITE_SUPABASE_ANON_KEY=your_supabase_anon_key
      # - AWS_ACCESS_KEY_ID=your_aws_access_key_id
      # - AWS_SECRET_ACCESS_KEY=your_aws_secret_access_key
    restart: unless-stopped
    volumes:
      # Optional: Mount kubeconfig directory if needed
      # - /path/to/kubeconfig:/root/.kube
      - logs:/app/logs

volumes:
  logs:
