version: '3'

services:
  kube-migrate:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8089:8089"
    environment:
      - NODE_ENV=production
      - DEPLOYMENT=production
      - PORT=8089
      - BACKEND_PORT=8089
      - FRONTEND_PORT=3009
      - VITE_K8S_PROXY_URL=/kube-migrate
      - VITE_API_PROXY_URL=/kube-migrate
      - VITE_AWS_REGION=us-east-1
      - VITE_COGNITO_USER_POOL_ID=us-east-1_0phCrx0Ao
      - VITE_COGNITO_CLIENT_ID=4qfs9mvg1phde56htj0d3b3ku9
      - VITE_DYNAMODB_REGION=us-east-1
    restart: always
    volumes:
      - kube-config:/app/.kube
    networks:
      - kube-migrate-network

networks:
  kube-migrate-network:
    driver: bridge

volumes:
  kube-config:
    driver: local
