apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lJQ243SStLdkppVkV3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TlRBME1UTXhNak0wTkRsYUZ3MHpOVEEwTVRFeE1qTTVORGxhTUJVeApFekFSQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLCkFvSUJBUUNwUDd1NzFXbFdjaU0vS2o2Y05GRFI3ZFNFQjcyS0liUFFMTW9QNDVhc2lWVFZBOTBsRlc5NUZqVWQKZFNNeThTK2tVWUNobVhrcUF0QUc2R2pDbm05Q0MwVVlpMUdSM0M0VnhPZGNvK2RDendWdk9HbGdpdVJ1NWxWbwpPY0RzZlNpcmNsL3o1NmsxcEdZRlZSdXIwSzlMV0tEYldqcW5ZUy9YRDBuZlpIZWYyb1JBOWFUWDl5SHgveURxClp0R3lZNXVOVkNlRDQrU2dHU2EvdTNmVDRyQkdCeitVY2V6Zm1aVzdsNWhmV29la1BZd2hvL014cEIvVExXVFkKVURLRFJ2KzV0a2ZFOWhsVURWU0hQSkVLQVQ1aEszUmpua1pyeUFZb2ZFc3UrQzJHRjZGTzBZQ0dtQXB1ditTOQpOQVhYa0hGalQrN0JBanNTeHN3WkxiS0EreGUvQWdNQkFBR2pXVEJYTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQCkJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJROEVkVWw2VmUwb3BhWEs3NXI4TGxlMEwrYmlUQVYKQmdOVkhSRUVEakFNZ2dwcmRXSmxjbTVsZEdWek1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQTFROTVuNWl4ZgpySXpJZ1N5amQ2K1QyMnl4anhsS1NCRVBXZ2xEYU51ZmZod0hkNHZFZ3oyUkxqM2xiNTVtTHFEVmVqR2VIYkg5CmhJendPYjd2ZnNzay9vQ0hLZEh2N0dLSjR6SlM4MzB4OW9tSE91aDA3eFFNZnRVVWZUS2FvK3prNWVUUmcrTXUKMUpyOG9rTFRMcm90R2x0cnA0M05GNkdDdnFhcytURDBtNlFvMHNSdm5aWG5kM1FFTlZWeW83NHBhY0RsVXBZdgovdnJMOG9lWmVhT2k4YmVoRXhzY2dYNkxZZ0NIYUNEd2NQNGdiM2puKy8wUnFBZjhnNlFVemltSXFOajRVYWUvCnBKb3NkcmdESjFJSzlkVE1Ud0h1OHU1NVVtWEVwQzU1ZlBjazMrdUJoNXhVa2U3N2NnVVQ3cHVNTlhEYXZYb2QKNkF2djhoMDNBODVVCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://9C8C0CC66D1AB9850686BB2414462CFC.gr7.us-west-2.eks.amazonaws.com
  name: arn:aws:eks:us-west-2:644483925103:cluster/multi-tenant-eks
contexts:
- context:
    cluster: arn:aws:eks:us-west-2:644483925103:cluster/multi-tenant-eks
    user: arn:aws:eks:us-west-2:644483925103:cluster/multi-tenant-eks
  name: arn:aws:eks:us-west-2:644483925103:cluster/multi-tenant-eks
current-context: arn:aws:eks:us-west-2:644483925103:cluster/multi-tenant-eks
kind: Config
preferences: {}
users:
- name: arn:aws:eks:us-west-2:644483925103:cluster/multi-tenant-eks
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - --region
      - us-west-2
      - eks
      - get-token
      - --cluster-name
      - multi-tenant-eks
      - --output
      - json
      command: aws
